name: web_dashboard_app_tut
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.5+3
  flutter_lints: ^2.0.0
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3
  firebase_auth: ^4.7.0
  firebase_storage: ^11.2.5
  flutter_datetime_picker: ^1.5.1
  intl: ^0.17.0
  image_picker_web: ^2.1.1
  qr_flutter: ^4.0.0
  file_picker: ^5.5.0
  pdf: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
