// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDUC9yClvRQ5A-SgogIO9pge6zHtQ6-yM',
    appId: '1:735594420343:web:979af67336cd3aeda78e72',
    messagingSenderId: '735594420343',
    projectId: 'perpustakaan-ccad6',
    authDomain: 'perpustakaan-ccad6.firebaseapp.com',
    storageBucket: 'perpustakaan-ccad6.appspot.com',
    measurementId: 'G-FQMKPRX985',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyIeHs41Q2SjW_pcqrbyyUV9yyfz5sWZo',
    appId: '1:735594420343:android:ea5baf84b4141015a78e72',
    messagingSenderId: '735594420343',
    projectId: 'perpustakaan-ccad6',
    storageBucket: 'perpustakaan-ccad6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1gA-NibLE6OVUu52xIXQPcq5PRnYRCwc',
    appId: '1:735594420343:ios:dbf80a86a512ca50a78e72',
    messagingSenderId: '735594420343',
    projectId: 'perpustakaan-ccad6',
    storageBucket: 'perpustakaan-ccad6.appspot.com',
    iosClientId: '735594420343-rsf62q0rtg7ebceesdilfo12udrlpcjo.apps.googleusercontent.com',
    iosBundleId: 'com.example.perpustakaanMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1gA-NibLE6OVUu52xIXQPcq5PRnYRCwc',
    appId: '1:735594420343:ios:61d2d21ae51e80a5a78e72',
    messagingSenderId: '735594420343',
    projectId: 'perpustakaan-ccad6',
    storageBucket: 'perpustakaan-ccad6.appspot.com',
    iosClientId: '735594420343-jlji0425mmdagg901n5qjf0vl4uh98p7.apps.googleusercontent.com',
    iosBundleId: 'com.example.perpustakaanMobile.RunnerTests',
  );
}
